// Generated by gencpp from file homework3/CustomMessage.msg
// DO NOT EDIT!


#ifndef HOMEWORK3_MESSAGE_CUSTOMMESSAGE_H
#define HOMEWORK3_MESSAGE_CUSTOMMESSAGE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace homework3
{
template <class ContainerAllocator>
struct CustomMessage_
{
  typedef CustomMessage_<ContainerAllocator> Type;

  CustomMessage_()
    : data(0.0)
    , text()  {
    }
  CustomMessage_(const ContainerAllocator& _alloc)
    : data(0.0)
    , text(_alloc)  {
  (void)_alloc;
    }



   typedef float _data_type;
  _data_type data;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _text_type;
  _text_type text;





  typedef boost::shared_ptr< ::homework3::CustomMessage_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::homework3::CustomMessage_<ContainerAllocator> const> ConstPtr;

}; // struct CustomMessage_

typedef ::homework3::CustomMessage_<std::allocator<void> > CustomMessage;

typedef boost::shared_ptr< ::homework3::CustomMessage > CustomMessagePtr;
typedef boost::shared_ptr< ::homework3::CustomMessage const> CustomMessageConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::homework3::CustomMessage_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::homework3::CustomMessage_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::homework3::CustomMessage_<ContainerAllocator1> & lhs, const ::homework3::CustomMessage_<ContainerAllocator2> & rhs)
{
  return lhs.data == rhs.data &&
    lhs.text == rhs.text;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::homework3::CustomMessage_<ContainerAllocator1> & lhs, const ::homework3::CustomMessage_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace homework3

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::homework3::CustomMessage_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::homework3::CustomMessage_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::homework3::CustomMessage_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::homework3::CustomMessage_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::homework3::CustomMessage_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::homework3::CustomMessage_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::homework3::CustomMessage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9d91e52075ccde6ed9c15ca415ec13ae";
  }

  static const char* value(const ::homework3::CustomMessage_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9d91e52075ccde6eULL;
  static const uint64_t static_value2 = 0xd9c15ca415ec13aeULL;
};

template<class ContainerAllocator>
struct DataType< ::homework3::CustomMessage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "homework3/CustomMessage";
  }

  static const char* value(const ::homework3::CustomMessage_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::homework3::CustomMessage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 data\n"
"string text\n"
;
  }

  static const char* value(const ::homework3::CustomMessage_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::homework3::CustomMessage_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
      stream.next(m.text);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CustomMessage_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::homework3::CustomMessage_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::homework3::CustomMessage_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "data: ";
    Printer<float>::stream(s, indent + "  ", v.data);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "text: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.text);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HOMEWORK3_MESSAGE_CUSTOMMESSAGE_H
