// Generated by gencpp from file FindOS/FollowMsg.msg
// DO NOT EDIT!


#ifndef FINDOS_MESSAGE_FOLLOWMSG_H
#define FINDOS_MESSAGE_FOLLOWMSG_H

#include <ros/service_traits.h>


#include <FindOS/FollowMsgRequest.h>
#include <FindOS/FollowMsgResponse.h>


namespace FindOS
{

struct FollowMsg
{

typedef FollowMsgRequest Request;
typedef FollowMsgResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct FollowMsg
} // namespace FindOS


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::FindOS::FollowMsg > {
  static const char* value()
  {
    return "95502f06d5d7105e5d4e01d38d46ad27";
  }

  static const char* value(const ::FindOS::FollowMsg&) { return value(); }
};

template<>
struct DataType< ::FindOS::FollowMsg > {
  static const char* value()
  {
    return "FindOS/FollowMsg";
  }

  static const char* value(const ::FindOS::FollowMsg&) { return value(); }
};


// service_traits::MD5Sum< ::FindOS::FollowMsgRequest> should match
// service_traits::MD5Sum< ::FindOS::FollowMsg >
template<>
struct MD5Sum< ::FindOS::FollowMsgRequest>
{
  static const char* value()
  {
    return MD5Sum< ::FindOS::FollowMsg >::value();
  }
  static const char* value(const ::FindOS::FollowMsgRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::FindOS::FollowMsgRequest> should match
// service_traits::DataType< ::FindOS::FollowMsg >
template<>
struct DataType< ::FindOS::FollowMsgRequest>
{
  static const char* value()
  {
    return DataType< ::FindOS::FollowMsg >::value();
  }
  static const char* value(const ::FindOS::FollowMsgRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::FindOS::FollowMsgResponse> should match
// service_traits::MD5Sum< ::FindOS::FollowMsg >
template<>
struct MD5Sum< ::FindOS::FollowMsgResponse>
{
  static const char* value()
  {
    return MD5Sum< ::FindOS::FollowMsg >::value();
  }
  static const char* value(const ::FindOS::FollowMsgResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::FindOS::FollowMsgResponse> should match
// service_traits::DataType< ::FindOS::FollowMsg >
template<>
struct DataType< ::FindOS::FollowMsgResponse>
{
  static const char* value()
  {
    return DataType< ::FindOS::FollowMsg >::value();
  }
  static const char* value(const ::FindOS::FollowMsgResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FINDOS_MESSAGE_FOLLOWMSG_H
