// Generated by gencpp from file FindOS/FollowMsgResponse.msg
// DO NOT EDIT!


#ifndef FINDOS_MESSAGE_FOLLOWMSGRESPONSE_H
#define FINDOS_MESSAGE_FOLLOWMSGRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace FindOS
{
template <class ContainerAllocator>
struct FollowMsgResponse_
{
  typedef FollowMsgResponse_<ContainerAllocator> Type;

  FollowMsgResponse_()
    : result()  {
    }
  FollowMsgResponse_(const ContainerAllocator& _alloc)
    : result(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::FindOS::FollowMsgResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::FindOS::FollowMsgResponse_<ContainerAllocator> const> ConstPtr;

}; // struct FollowMsgResponse_

typedef ::FindOS::FollowMsgResponse_<std::allocator<void> > FollowMsgResponse;

typedef boost::shared_ptr< ::FindOS::FollowMsgResponse > FollowMsgResponsePtr;
typedef boost::shared_ptr< ::FindOS::FollowMsgResponse const> FollowMsgResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::FindOS::FollowMsgResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::FindOS::FollowMsgResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::FindOS::FollowMsgResponse_<ContainerAllocator1> & lhs, const ::FindOS::FollowMsgResponse_<ContainerAllocator2> & rhs)
{
  return lhs.result == rhs.result;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::FindOS::FollowMsgResponse_<ContainerAllocator1> & lhs, const ::FindOS::FollowMsgResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace FindOS

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::FindOS::FollowMsgResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::FindOS::FollowMsgResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::FindOS::FollowMsgResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::FindOS::FollowMsgResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::FindOS::FollowMsgResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::FindOS::FollowMsgResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::FindOS::FollowMsgResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c22f2a1ed8654a0b365f1bb3f7ff2c0f";
  }

  static const char* value(const ::FindOS::FollowMsgResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc22f2a1ed8654a0bULL;
  static const uint64_t static_value2 = 0x365f1bb3f7ff2c0fULL;
};

template<class ContainerAllocator>
struct DataType< ::FindOS::FollowMsgResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "FindOS/FollowMsgResponse";
  }

  static const char* value(const ::FindOS::FollowMsgResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::FindOS::FollowMsgResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string result  # 响应消息\n"
;
  }

  static const char* value(const ::FindOS::FollowMsgResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::FindOS::FollowMsgResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FollowMsgResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::FindOS::FollowMsgResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::FindOS::FollowMsgResponse_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "result: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FINDOS_MESSAGE_FOLLOWMSGRESPONSE_H
