// Generated by gencpp from file FindOS/navigate_msg.msg
// DO NOT EDIT!


#ifndef FINDOS_MESSAGE_NAVIGATE_MSG_H
#define FINDOS_MESSAGE_NAVIGATE_MSG_H

#include <ros/service_traits.h>


#include <FindOS/navigate_msgRequest.h>
#include <FindOS/navigate_msgResponse.h>


namespace FindOS
{

struct navigate_msg
{

typedef navigate_msgRequest Request;
typedef navigate_msgResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct navigate_msg
} // namespace FindOS


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::FindOS::navigate_msg > {
  static const char* value()
  {
    return "95502f06d5d7105e5d4e01d38d46ad27";
  }

  static const char* value(const ::FindOS::navigate_msg&) { return value(); }
};

template<>
struct DataType< ::FindOS::navigate_msg > {
  static const char* value()
  {
    return "FindOS/navigate_msg";
  }

  static const char* value(const ::FindOS::navigate_msg&) { return value(); }
};


// service_traits::MD5Sum< ::FindOS::navigate_msgRequest> should match
// service_traits::MD5Sum< ::FindOS::navigate_msg >
template<>
struct MD5Sum< ::FindOS::navigate_msgRequest>
{
  static const char* value()
  {
    return MD5Sum< ::FindOS::navigate_msg >::value();
  }
  static const char* value(const ::FindOS::navigate_msgRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::FindOS::navigate_msgRequest> should match
// service_traits::DataType< ::FindOS::navigate_msg >
template<>
struct DataType< ::FindOS::navigate_msgRequest>
{
  static const char* value()
  {
    return DataType< ::FindOS::navigate_msg >::value();
  }
  static const char* value(const ::FindOS::navigate_msgRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::FindOS::navigate_msgResponse> should match
// service_traits::MD5Sum< ::FindOS::navigate_msg >
template<>
struct MD5Sum< ::FindOS::navigate_msgResponse>
{
  static const char* value()
  {
    return MD5Sum< ::FindOS::navigate_msg >::value();
  }
  static const char* value(const ::FindOS::navigate_msgResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::FindOS::navigate_msgResponse> should match
// service_traits::DataType< ::FindOS::navigate_msg >
template<>
struct DataType< ::FindOS::navigate_msgResponse>
{
  static const char* value()
  {
    return DataType< ::FindOS::navigate_msg >::value();
  }
  static const char* value(const ::FindOS::navigate_msgResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FINDOS_MESSAGE_NAVIGATE_MSG_H
